services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: ${APP_ENV}
      args: # This is needed to have access to env inside of Dockerfile
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: always
    env_file: # This is needed to set system-environment-variables (not available in Dockerfile).
      - .env

networks:
  default:
    external: true
    name: intranet
